### ISSUE TITLE
Compilation error with Magento 2.4.2

### ISSUE THREAD

**Issue by kiber** [yireo/magento2-replace-inventory#13]
I think the latest version (4.2.0) of this module is not compatible with Magento 2.4.2.

When I run `bin/magento setup:di:compile` command, I am getting an error

```
Compilation was started.
Interceptors generation... 4/9 [============>---------------]  44% 23 secs 358.0 MiB
In Generator.php line 139:
                                                                                                                                                         
  Class Magento\InventorySalesApi\Api\StockResolverInterface does not exist                                                                              
  Class Magento\InventoryCatalogFrontendUi\Controller\Product\GetQty\Interceptor generation error: The requested class did not generate properly, because the 'generated' directory permission is read-only. If --- after running the 'bin/magento setup:di:compile' CLI command when the 'generated' directory permission is set to write --- the requested class did not generate properly, then you must add the generated class object to the signature of the related construct method, only.                                                                                                                      
```

I think we should also add `Magento_InventoryCatalogFrontendUi` and other extensions to the replace list.

**Comment by jissereitsma** [comment]
Thanks for posting. Unfortunately, 2.4.2 is not released to the public yet, so I don't have any means to check for this.

Indeed, it makes sense that 2.4.2 adds new composer packages that also need replacing through the meta-package in this repo. Note that we are not replacing Magento modules (`A_B`) but composer packages (`a/b`). My educated guess is that the module `Magento_InventoryCatalogFrontendUi` is shipped in a composer package `magento/module-inventory-catalog-frontend-ui` but I can't now for sure - but I guess you can. 

This is now committed (https://github.com/yireo/magento2-replace-inventory/commit/58d66ec25cfef7a5bd8821b810d98ac14a49caa0) and released as 4.2.1 - but again untested, because Magento 2.4.2 has **not** been released yet.
