### ISSUE TITLE
Magento 2.4.3 

### ISSUE THREAD

**Issue by barryvdh** [yireo/magento2-replace-inventory#14]
Magento 2.4.3 is released. It looks like it adds these modules:

```
  - Installing magento/module-inventory-quote-graph-ql (1.0.0): Extracting archive
  - Installing magento/module-inventory-catalog-search-configurable-product (1.0.0): Extracting archive
  - Installing magento/module-inventory-catalog-search-bundle-product (1.0.0): Extracting archive
```

**Comment by jissereitsma** [comment]
Thanks. Committed as https://github.com/yireo/magento2-replace-inventory/commit/e9659996a9ee3c778f5085b9378416a946b47ac5 Will release right away

**Comment by jissereitsma** [comment]
Release https://github.com/yireo/magento2-replace-inventory/releases/tag/4.2.5

**Comment by barryvdh** [comment]
Shouldn't the new version be 4.3.0, to follow the naming system?

**Comment by jissereitsma** [comment]
I'm abandoning this whole naming system, because releasing a new minor (plus maintaining its branch on the long run) per patch release of Magento (well, 2.4.3 for instance) is cumbersome. And after experimenting with this, it appears that having a new release with replacements of 2.4.3 packages, while that release is then used for 2.4.2 (where those replacements are referring to non-existing packages), is actually totally harmful. In other words, replacing non-existing packages is totally fine.

Before the 2.4.3 release, I refactored things because of this, so that there is only a `magento-2.4` and `magento-2.3` branch (with a corresponding `4.y.z` and `3.y.z` major), but the minor will only sporadically be updated. Hence, the 4.2.5 release that no longer correlates to Magento versioning.

I've made more shifts in strategies with these packages, than anywhere else. I think that mostly is due to the undocumented nature of the composer `replace` trick, plus me making rookie mistakes because of this. But I try to not break things anymore :)
