### ISSUE TITLE
module-sales-inventory Incorrectly Disabled

### ISSUE THREAD

**Issue by Swiftless** [yireo/magento2-replace-inventory#5]
As per Magento DevDocs, SalesInventory module is not part of the MSI extension:
https://devdocs.magento.com/extensions/inventory-management/

Disabling this module breaks the "Return to Stock" feature when creating Credit Memos.

This line needs to be removed:
"magento/module-sales-inventory": "*"

Unless I am missing something?

**Comment by jissereitsma** [comment]
The module is now removed from the listing, so this should be solved. Thanks for addressing this!

**Comment by barryvdh** [comment]
This is not picked up with the current tag. You can get it with `dev-magento-2.3.5` as requirement. Maybe a 2.3.5.1 release can be tagged?
For the record, the error we encounted was 'Plugin class Magento\InventoryCatalog\Plugin\Catalog\Model\ResourceModel\Product\DeleteSourceItemsPlugin doesn't exist', which is solved by the latest version.

**Comment by jissereitsma** [comment]
Indeed the release was not yet made (branch exists, but tag & release need to be created following from this). Now it should be updated.

**Comment by barryvdh** [comment]
Wait, did you remove and recreate the tags? You should avoid doing that, because composer caches the info. So you might not get the new version when you have the old one installed. Also, this could lead to different installs, eg the old one locally and the updated tag on the live server (or other way around because it's cached on the line server).

**Comment by jissereitsma** [comment]
Thanks for that pointer. Yes, the tags and releases were removed and then recreated (by script) but as you point out, that would not be the best of solutions. Creating new incremental releases would be better. However, if a Magento version `2.X.Y` is only supported by a specific branch, this would logically mean that the branch would be labeled `2.X.Y` as well (or actually `magento-2.X.Y`) which leads to that 3 out of the 3 numbers of semantic versioning are in use already. Perhaps a fourth number could be uses as version / tag / release name (`2.X.Y.Z`) so that many incremental changes can be introduced for one major Magento release (`2.3.5.2432`).

What I don't know is whether composer properly supports this as semantic versioning. Any ideas?

**Comment by barryvdh** [comment]
I think requiring `composer require 2.3.5.*` would work if you tag `2.3.5.0`, `2.3.5.1` etc

**Comment by jissereitsma** [comment]
Cross-fingers, but the scripts for managing all these repos (https://github.com/yireo/magento2-replace-tools) are now rewritten for having these additional release numbers (https://github.com/yireo/magento2-replace-inventory/releases).

**Comment by barryvdh** [comment]
Cool, don't forget to update the readme then
